### ISSUE TITLE
Django library packed in windows binary

### ISSUE THREAD

**Issue by tibor-vavra** [Artanidos/EbookCreator#1]
Hi,
thank you for your project.

In binary distribution for Windows I found Django library too. It is 24MB.

List of files in bin folder: 
**django\**
**Django-2.2.3-py3.7.egg-info\**
Include\
PyQt5\
pytz\
main.exe.manifest
main.exe
base_library.zip
Qt5QuickWidgets.dll
Qt5WebEngineWidgets.dll
python3.dll
libssl-1_1-x64.dll
libcrypto-1_1-x64.dll
sqlite3.dll
Qt5PrintSupport.dll
Qt5PositioningQuick.dll
LIBEAY32.dll
MSVCP140.dll
Qt5Sql.dll
Qt5QuickParticles.dll
Qt5XmlPatterns.dll
Qt5Multimedia.dll
Qt5Test.dll
Qt5QuickTest.dll
Qt5Svg.dll
Qt5WebSockets.dll
Qt5WebChannel.dll
Qt5WebEngine.dll
Qt5WebEngineCore.dll
Qt5Bluetooth.dll
Qt5RemoteObjects.dll
Qt5Nfc.dll
Qt5Location.dll
Qt5DBus.dll
Qt5Sensors.dll
Qt5QuickShapes.dll
Qt5Widgets.dll
Qt5SerialPort.dll
Qt5QuickControls2.dll
Qt5QuickTemplates2.dll
libGLESv2.dll
Qt5Network.dll
Qt5Positioning.dll
Qt5Qml.dll
Qt5Core.dll
Qt5Gui.dll
Qt5Quick.dll
select.pyd
_socket.pyd
_lzma.pyd
_bz2.pyd
_hashlib.pyd
pyexpat.pyd
unicodedata.pyd
_ssl.pyd
_decimal.pyd
_contextvars.pyd
_queue.pyd
_sqlite3.pyd
_ctypes.pyd
python37.dll
VCRUNTIME140.dll

**Comment by Artanidos** [comment]
Should be fixed with release 1.3.1
