### ISSUE TITLE
Crash after creating new ebook project

### ISSUE THREAD

**Issue by tibor-vavra** [Artanidos/EbookCreator#2]
On Windows 10 platform it crashes after creating a new ebook project.

Create a new ebook project
![image](https://user-images.githubusercontent.com/4319021/61442178-6859d280-a947-11e9-9002-a6c788c55835.png)

Fill all fields in the wizard
![image](https://user-images.githubusercontent.com/4319021/61441925-e36eb900-a946-11e9-8edc-1bc24184b00c.png)

After Finish it crash
![image](https://user-images.githubusercontent.com/4319021/61441948-ebc6f400-a946-11e9-8268-5a9e0fdfb2f8.png)

No error message, just crash

**Comment by johnblommers** [comment]
The program core dumps when I click on the settings or add a new chapter. I'm  running Pop!_OS 19.04 which is based on Ubuntu 19.04.

**Comment by Artanidos** [comment]
Should be fixed with release 1.3.1
